export const BILLING_ERROR_CODES = {
  CUSTOMER_NOT_FOUND: "BILLING_CUSTOMER_NOT_FOUND",
  CUSTOMER_CREATE_FAILED: "BILLING_CUSTOMER_CREATE_FAILED",
  CHECKOUT_SESSION_FAILED: "BILLING_CHECKOUT_SESSION_FAILED",
  PAYMENT_NOT_FOUND: "BILLING_PAYMENT_NOT_FOUND",
  PAYMENT_CREATE_FAILED: "BILLING_PAYMENT_CREATE_FAILED",
  PAYMENT_UPDATE_FAILED: "BILLING_PAYMENT_UPDATE_FAILED",
  WEBHOOK_VERIFICATION_FAILED: "BILLING_WEBHOOK_VERIFICATION_FAILED",
  WEBHOOK_PROCESSING_FAILED: "BILLING_WEBHOOK_PROCESSING_FAILED",
  SUBSCRIPTION_NOT_FOUND: "BILLING_SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_EXISTS: "BILLING_SUBSCRIPTION_ALREADY_EXISTS",
  SUBSCRIPTION_CANCEL_FAILED: "BILLING_SUBSCRIPTION_CANCEL_FAILED",
  SUBSCRIPTION_UPDATE_FAILED: "BILLING_SUBSCRIPTION_UPDATE_FAILED",
  /** @deprecated Use CHECKOUT_SESSION_FAILED instead */
  SUBSCRIPTION_CHECKOUT_SESSION_FAILED:
    "BILLING_SUBSCRIPTION_CHECKOUT_SESSION_FAILED",
  INVOICE_NOT_FOUND: "BILLING_INVOICE_NOT_FOUND",
  INVOICE_PROCESSING_FAILED: "BILLING_INVOICE_PROCESSING_FAILED",
  PRODUCT_NOT_FOUND: "BILLING_PRODUCT_NOT_FOUND",
  PRODUCT_CREATE_FAILED: "BILLING_PRODUCT_CREATE_FAILED",
  PRODUCT_UPDATE_FAILED: "BILLING_PRODUCT_UPDATE_FAILED",
  PRODUCT_ARCHIVE_FAILED: "BILLING_PRODUCT_ARCHIVE_FAILED",
  PRODUCT_NOT_SYNCED: "BILLING_PRODUCT_NOT_SYNCED",
  PRODUCT_CANNOT_ARCHIVE_VIA_UPDATE:
    "BILLING_PRODUCT_CANNOT_ARCHIVE_VIA_UPDATE",
  PRICE_NOT_FOUND: "BILLING_PRICE_NOT_FOUND",
  PRICE_CREATE_FAILED: "BILLING_PRICE_CREATE_FAILED",
  PRICE_ARCHIVE_FAILED: "BILLING_PRICE_ARCHIVE_FAILED"
} as const
export type BillingErrorCode =
  (typeof BILLING_ERROR_CODES)[keyof typeof BILLING_ERROR_CODES]
