export const NOTIFICATION_ERROR_CODES = {
  NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  CREATE_FAILED: "NOTIFICATION_CREATE_FAILED",
  ALREADY_CANCELLED: "NOTIFICATION_ALREADY_CANCELLED",
  ALREADY_COMPLETED: "NOTIFICATION_ALREADY_COMPLETED",
  NOT_SCHEDULED: "NOTIFICATION_NOT_SCHEDULED"
} as const

export type NotificationErrorCode =
  (typeof NOTIFICATION_ERROR_CODES)[keyof typeof NOTIFICATION_ERROR_CODES]
