export const AUTH_ERROR_CODES = {
  AUTH_ADMIN_UNAUTHORIZED: "AUTH_ADMIN_UNAUTHORIZED",
  AUTH_USER_UNAUTHORIZED: "AUTH_USER_UNAUTHORIZED"
} as const
export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES]
